version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "./package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "./package.json" }}
      - run: yarn test

  deploy:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "./package.json" }}
          - v1-dependencies-
      - run: yarn install
      - run:
          name: deploy to gas
          command: |
            yarn deploy

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master


  deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
